name: lms_boilerplate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  app_links: ^6.3.2
  device_info_plus: ^10.1.2
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_onboarding_slider: ^1.0.11
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  http_parser: ^4.0.2
  modal_progress_hud_nsn: ^0.5.1
  pretty_dio_logger: ^1.4.0
  logger: ^2.4.0
  url_launcher: ^6.3.1
  connectivity_plus: ^6.0.5
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/pngs/
    - assets/svgs/
    - assets/gifs/

